baseURL = 'http://example.com/'
contentDir = "content/ja/"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

title = 'Nimos'
offlineSearch = true

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false


[author]
  name = "hiyoko"
  homepage = "https://twitter.com/Jewel_Flash"

[params]
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"

[[menu.main]]
    name = "Docs"
    weight = 100
    url = "/docs/"
    
[[menu.main]]
    name = "Community"
    weight = 200
    url = "/community/"
    
[[menu.main]]
    name = "About"
    weight = 1000
    url = "/about/"

[params.links]
[[params.links.user]]
	name = "Join Our Discord Server!"
	url = "https://discord.com/invite/veRBTjY8aK"
	icon = "fab fa-discord"
        desc = "Chat with other users and project developers"
[[params.links.user]]
	name = "Developper Twitter"
	url = "https://twitter.com/Jewel_Flash"
	icon = "fab fa-twitter"
        desc = "個人的なつぶやきが主ですが、リリース告知とかもするかもです。"
[[params.links.user]]
	name = "Developper's YouTube CH"
	url = "https://www.youtube.com/channel/UCN8MGXWBoMnB1uLZ5ptlz-g"
	icon = "fab fa-youtube"
        desc = "今はまだ無いが、Nimosの説明動画などを上げる可能性があります。"
[[params.links.user]]
	name = "Download Nimos"
	url = "https://github.com/hiyok0/Nimos/releases"
	icon = "fas fa-arrow-circle-down"
        desc = "今はまだ無いが、Nimosの説明動画などを上げる可能性があります。"
[[params.links.developer]]
	name = "GitHub　hiyok0/Nimos"
	url = "https://github.com/hiyok0/Nimos/"
	icon = "fab fa-github"
        desc = "バグを修正したい？機能追加をしたい？どうぞこちらに。Folk me on GitHub!"
[[params.links.developer]]
	name = "GitHub　hiyok0/NimosWebsite"
	url = "https://github.com/hiyok0/NimosWebsite/"
	icon = "fas fa-book"
        desc = "一緒にこのドキュメントを充実させましょう！"
